name: Reusable GKE Deploy Workflow

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      docker-context:
        required: true
        type: string
      docker-tag:
        required: false
        type: string
        default: latest
      k8s-path:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker image to Artifact Registry
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-repository/${{ inputs.service-name }}:${{ inputs.docker-tag }} ${{ inputs.docker-context }}
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-repository/${{ inputs.service-name }}:${{ inputs.docker-tag }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl apply --validate=false -f ${{ inputs.k8s-path }}/deployment.yaml
          kubectl apply --validate=false -f ${{ inputs.k8s-path }}/service.yaml
