name: Python application

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        default: '3.13'
        type: string
      coverage-folder:
        required: false
        default: 'app'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov codecov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=13 --max-line-length=127 --statistics

      - name: Run tests (Docker or local)
        run: |
          if [ -f docker-compose.yml ]; then
            docker compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from test
          else
            if [ -d "${{ inputs.coverage-folder }}" ]; then \
              pytest --cov=${{ inputs.coverage-folder }} --cov-report=xml; \
            else \
              pytest; \
            fi
          fi

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
